sudo: required
services:
    - docker
before_install:
    - docker build -t robertoperillo/react-tests -f ./client/Dockerfile.dev ./client
script:
    - docker run robertoperillo/react-tests npm test -- --coverage
after_success:
    - docker build -t robertoperillo/multi-client ./client
    - docker build -t robertoperillo/multi-nginx ./nginx
    - docker build -t robertoperillo/multi-server ./server
    - docker build -t robertoperillo/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push robertoperillo/multi-client
    - docker push robertoperillo/multi-nginx
    - docker push robertoperillo/multi-server
    - docker push robertoperillo/multi-worker
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-474997196961
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY